### DISCUSSION TITLE
Easy set away card. Also great to e.g quickly but temporary rise temperature

### DISCUSSION THREAD

**Discussion by dbuezas** [dbuezas/eq3btsmart#72] [Show and tell]
Make helpers in the Home Assistant UI under devices/helpers:
* A select with tour thermostat ids
* an input for temperature
* an input for hours 

Add these two scripts from the UI under Automation/scripts

```yaml
alias: Heating Set Away Single
variables:
  radiator_dropdown: "{{ states('input_select.radiator_away_dropdown') }}"
  radiator_hours: "{{ states('input_select.radiator_away_hours') }}"
  radiator_temperature: "{{ states('input_number.radiator_away_temperature') }}"
sequence:
  - service: switch.turn_off
    target:
      entity_id: switch.{{ radiator_dropdown }}_away
  - service: number.set_value
    data:
      value: "{{ radiator_hours }}"
    target:
      entity_id: number.{{ radiator_dropdown }}_away_hours
  - service: number.set_value
    data:
      value: "{{ radiator_temperature }}"
    target:
      entity_id: number.{{ radiator_dropdown }}_away
  - service: switch.turn_on
    target:
      entity_id: switch.{{ radiator_dropdown }}_away
mode: parallel
icon: mdi:calendar-end
max: 10
```

```yaml
alias: Heating cancel away single
sequence:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.{{states('input_select.radiator_away_dropdown')}}_away
mode: parallel
max: 10
```
![Screenshot_20231202-153118](https://github.com/dbuezas/eq3btsmart/assets/777196/3d9d81e5-b475-4812-a20d-b8cf854b85bf)

```yaml
type: entities
entities:
  - entity: input_select.radiator_away_dropdown
    name: Thermostat
  - entity: script.heating_cancel_away_single
    name: Cancel
    icon: mdi:close
  - entity: input_select.radiator_away_hours
    name: Hours
  - entity: input_number.radiator_away_temperature
    name: Temperature
  - entity: script.heating_set_away_single
    name: Set
title: Temporary temperature
```

Done!
