### ISSUE TITLE
Cannot lock TRV with automation in HA

### ISSUE THREAD

**Issue by G-S-E** [dbuezas/eq3btsmart#56]
``` 
id: '1676912753979'
alias: LOCK TRVs
description: Lock all TRVs
trigger: []
condition: []
action:
  - device_id: bb0e4c4fd82ddb9358ea572131cd4f7d
    domain: lock
    entity_id: lock.trv_living_room_big_locked
    type: lock
  - device_id: 88a3ee930c6a5b8c0018b98d70705a7a
    domain: lock
    entity_id: lock.trv_living_room_small_locked
    type: lock
  - device_id: d005c810c8d5f8e17fa5f252e1005e12
    domain: lock
    entity_id: lock.trv_corridor_locked
    type: lock
  - device_id: d694c8dfe5c0cd59da4530a2a2394631
    domain: lock
    entity_id: lock.trv_wc_locked
    type: lock
  - device_id: ebd2877034e66b152803607c71e676e5
    domain: lock
    entity_id: lock.trv_office_locked
    type: lock
  - device_id: 2f180db4fe772e6cd034a1ad835b8c06
    domain: lock
    entity_id: lock.trv_bedroom_locked
    type: lock
  - device_id: 56177077ef7d1b9175660f2d2eb5f85d
    domain: lock
    entity_id: lock.trv_bathroom_locked
    type: lock
mode: single
```
Trace gives the following:
![image](https://user-images.githubusercontent.com/6448163/220168190-9cfae898-2518-4c75-b687-d0ee843a377a.png)
