### ISSUE TITLE
BTProxy support

### ISSUE THREAD

**Issue by SirYaro** [dbuezas/eq3btsmart#61]
Hi.
Is there any special (per device) configuration required for esp32 bluetooth proxy to work with this integration?

I have both 
```
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
```
and
```
bluetooth_proxy:
  active: true
```
setup on all my esps (3pcs) and half of my eq3 (those outside bt dongle range) are still not visible...
