### ISSUE TITLE
[EQ-3] Error updating: Device not found

### ISSUE THREAD

**Issue by andycockerill-cpi** [dbuezas/eq3btsmart#71]
I'm using an Esphome BT proxy with the following config:

```
esphome:
  name: office-bluetooth
  friendly_name: office-bluetooth

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  

ota:
  

wifi:
  

  ap:
    

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
```

I get entries in the HA logs like:

```
This error originated from a custom integration.

Logger: custom_components.dbuezas_eq3btsmart.climate
Source: custom_components/dbuezas_eq3btsmart/climate.py:326
Integration: eQ-3 Bluetooth Smart Thermostats (dbuezas) (documentation, issues)
First occurred: 15:30:10 (2 occurrences)
Last logged: 15:40:13

[EQ-3] Error updating: Device not found
```

I'm running HA in K8S on a Raspberry PI 4.
